### ISSUE TITLE
Chromebook Install Failed for ESP32-V2

### ISSUE THREAD

**Issue by lorennorman** [adafruit/littlefs-pure-js#1]
Installing on a Chromebook with ChromeOS v 92.0.4515.162 64-bit (just realized this needs updating...)

Attempting to install via [the WipperSnapper Firmware Tool](https://adafruit.github.io/WipperSnapper_Firmware_Uploader/) and an ESP32-V2. The entire install process went swimmingly until the very end, when it gave the error below and did not complete (at least not visibly.)

The progress indicator hung at: `Generating and Flashing LittleFS Partition (6/6)...` and the progress bar shows 100% green.

Got `TypeError: invalid_arguement` on `littlefs.js:716`

I snapped a pic of the stack trace (above the yellow line can be ignored, i believe):
![Image from iOS (4)](https://user-images.githubusercontent.com/17697/162509476-e3859fd0-39e9-4746-a7e8-899b2c85c511.jpg)

**Comment by makermelissa** [comment]
Well, it's not happening on regular chrome with the V2. I _might_ be able to get my hands on an old Chromebook that's missing a screen. I'm not even sure if it will run the latest chrome OS, but I'll find out.

Also, can you try updating and trying again?

**Comment by makermelissa** [comment]
I forgot to mention, I manually tried running the command in the console (modified slightly to run outside of a class) and it seemed perfectly with the syntax of the functions.

**Comment by lorennorman** [comment]
Thanks for giving this a look, I will:
- update the Chromebook
- try that board again
- try the other boards
- report back!

**Comment by makermelissa** [comment]
Sounds good. I was able to get my hands on the chromebook. Its version of chrome is probably even more outdated than yours though, so I'll wait to hear back if you had any improvements.

**Comment by makermelissa** [comment]
Loren tried this after updating to the latest version of Chromium and the error went away. So really, it only seems to be an issue on older chromebooks that are unable to update to the latest version.
